/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
static yyconst short int yy_accept[397] =
    {   0,
        0,    0,   18,   17,   17,   17,    2,   17,   17,   17,
       17,   17,    1,    0,    0,    0,    0,    0,    0,    0,
        2,    0,    2,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,
        0,    0,    6,    0,   12,    7,   16,    0,    0,    0,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        6,    0,    0,    0,    0,    0,   13,    0,    0,    0,
        0,    0,    0,   14,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    8,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    5,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    7,    1,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,    1,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   24,   24,   27,   24,   28,
       29,   24,   24,   30,   31,   32,   33,   24,   34,   24,
       24,   24,   35,    1,   36,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    2,    1,    1,    3,    4,    5,    5,    1,    4,
        6,    7,    8,    9,   10,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    1,    1
    } ;

static yyconst short int yy_base[457] =
    {   0,
        0,    0, 1013, 1255,  995,   35,   45,  994,   29,   27,
       37,   33,   48,   61,   59,    0,   70,   47,   72,   73,
       89,  105,   71,  988,   55,   72,   82,   76,   74,  987,
       90,   91,   92,   97,  115,  976,  975,  976,  107,  108,
      119,  969,  118,  113, 1255, 1255, 1255,  117,  122,  125,
      139,  117,  131,  114,  968,   28,  138,  966,  131,  139,
      967,  142,  146,  153,  160,  160,  167,  177,  170,  169,
      141,  174,  180,  183,  190,  959, 1255,  190,  197,  200,
      191,  956,  957, 1255,  203,  206,  213,  954,  194,  216,
      217,  225,  230,  228,  228,  235,  246,  244,  247,  250,

      233,  245,  264,  270,  959,  214,  271,  264,  954,  268,
      275,  282,  289,    0,    0,  953, 1255,  289,  296,  299,
      312,  259,  306,  304,  313,  314, 1255,  315,  323,  324,
      327,  321,  334,  341,  961,  351,  335,  358,  359,  360,
      361,  377,  393,  363,  364,  375,  379, 1255,  359,  371,
      388,  402,  386,  950,  413,  947,  400,  401,  420,  944,
      926,  927,  412,  413,  423,  410,  418,  422, 1255,  417,
      898,  430,  435,  438,  439,  442,  916,  468,  443,  446,
      444,  451,  921,  909,  453,  913,  466,   86,  469,  485,
      465,  482,  488,  504,  520,  483,  486,  490,  502,  916,

      901,  503,  491,  507,  912,  521,  524,  154,  515,  512,
      537,  911,  910,  911,  529,  532,  545, 1255,  890,  905,
      533,  541,  239,  899,  553,  283,  879,  550,  555,  531,
      562,  554,  897,  891,  575,  377,  557,  569,  582,  901,
      574,  591, 1255,  584,  892,  587,  584,  589,  463,    0,
        0,  889,  593,  600,  564,  602,  863,  590,  603,  608,
      606,  611,  622,  860,  613,  615,  623,  627,  620,  869,
      640,  633,  625,  848,  637,  639,  641,  831,  653,  646,
      669,  648,  655,  652,  656,  824,  680,  817,  687,  680,
      681,  657,  694,  814,  686,  703,  711,  683,  705,  707,

      723,  739,  699,  717,  715,  725,  728,    0,    0,  796,
      726,  741,  743,  748,  760,  710,  749,  752,  762,  754,
      766,  773,  738,  733,  758,  759,  770,  697,  694,  782,
      762,  769,  642,  778,  781,  786,  791,  789,  647,  618,
      575,  802,  574, 1255,  790,  540,  796,  800,  803,  810,
      810,  812,  813,  501,  814,  821,  823,  470,  457,  824,
      828,  831,  441,  842,  835,  423,  849,  842,  843,  847,
      860,  398,  848,  867,    0,    0,  383,  859,  862,  869,
      872,  335,  869,  876,  877,  336,  889,  883,  887,  303,
      899,  275,  894,  247,  179, 1255,  906,  913,  924,  929,

      931,  935,  937,  939,  942,  948,  954,  964,  966,  968,
      979,  983,  989,  991,  996,  999, 1006, 1017, 1027, 1038,
     1043, 1045, 1047, 1058, 1060, 1066, 1077, 1083, 1088, 1090,
     1101, 1103, 1109, 1114, 1116, 1122, 1129, 1135, 1137, 1139,
     1150, 1161, 1167, 1172, 1183, 1190, 1195, 1197, 1199, 1205,
     1211, 1213, 1224, 1230, 1235, 1242
    } ;

static yyconst short int yy_def[457] =
    {   0,
      396,    1,  396,  396,  396,  396,  397,  398,  398,  398,
      398,  398,  396,  396,  396,    6,  396,  399,  399,  399,
      396,  397,   21,  398,  398,  398,  398,  398,  398,  396,
      396,  396,  399,  400,  399,  396,  396,   23,  398,  398,
      396,  401,  398,  398,  396,  396,  396,  396,  400,  396,
      398,  398,  402,  401,  403,  398,  396,  404,  398,  405,
      396,  405,  396,  402,  396,  406,  403,  398,  407,  404,
      398,  405,  408,  405,  396,  396,  396,  396,  406,  396,
      396,  409,  396,  396,  396,  407,  396,  410,  396,  396,
      408,  396,  411,  396,  412,  409,  411,  396,  413,  410,

      396,  414,  396,  411,  396,  415,   97,  416,  396,  416,
      396,  412,  396,   97,  417,  396,  396,  396,  413,  396,
      418,  414,  414,  414,  414,  396,  396,  396,  415,  396,
      416,  419,  416,  396,  396,   97,  396,  396,  420,  420,
      420,  396,  418,  142,  414,  414,  414,  396,  396,  396,
      396,  419,  396,  396,   97,  396,  420,  421,  420,  396,
      396,  144,  414,  414,  414,  396,  422,  396,  396,  396,
      396,  396,  421,  396,  414,  414,  423,  424,  422,  422,
      422,  422,  396,  396,  396,  425,  414,  426,  423,  396,
      427,  427,  427,  396,  424,  194,  422,  422,  422,  396,

      396,  428,  425,  414,  396,  396,  426,  396,  427,  429,
      427,  396,  396,  196,  422,  422,  422,  396,  396,  396,
      396,  428,  396,  430,  431,  396,  396,  396,  429,  396,
      422,  422,  432,  396,  431,  396,  433,  430,  431,  396,
      434,  235,  396,  396,  435,  422,  436,  432,  396,  235,
      437,  396,  396,  433,  396,  396,  396,  396,  434,  396,
      438,  435,  422,  396,  396,  436,  396,  396,  439,  396,
      235,  396,  396,  396,  396,  438,  396,  440,  441,  396,
      442,  439,  439,  439,  439,  396,  235,  396,  441,  396,
      443,  440,  441,  396,  444,  289,  396,  445,  445,  445,

      396,  442,  301,  439,  439,  439,  396,  289,  446,  396,
      396,  443,  396,  396,  396,  396,  444,  396,  445,  447,
      445,  396,  396,  303,  439,  439,  439,  396,  396,  289,
      396,  396,  396,  396,  447,  396,  439,  439,  448,  396,
      396,  289,  396,  396,  396,  449,  439,  450,  448,  396,
      451,  449,  439,  396,  396,  450,  396,  396,  396,  396,
      451,  396,  452,  453,  396,  396,  453,  396,  454,  452,
      453,  396,  455,  367,  367,  456,  396,  396,  454,  396,
      396,  396,  396,  455,  396,  396,  367,  396,  396,  396,
      367,  396,  396,  396,  396,    0,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396
    } ;

static yyconst short int yy_nxt[1292] =
    {   0,
        4,    4,    4,    4,    4,    4,    5,    5,    4,    4,
        6,    4,    4,    4,    4,    4,    7,    8,    8,    9,
       10,    8,    8,    8,    8,   11,    8,    8,    8,    8,
        8,    8,    8,   12,    4,    4,   14,   23,   23,   23,
       15,   15,   15,   23,   15,   16,   17,   23,   33,   68,
       18,   19,   20,   25,   18,   26,   30,   29,   13,   27,
       31,   21,   14,   34,   28,   23,   15,   15,   15,   32,
       15,   17,   39,   33,   33,   18,   18,   18,   36,   18,
       37,   23,   23,   41,   23,   42,   23,  396,   34,   34,
       17,   31,   23,   33,   18,   19,   20,  205,   18,   44,

       32,   32,  206,   46,   40,   21,  396,   43,   34,   47,
      396,  396,  396,   48,  396,   38,  396,   23,   23,   55,
       41,  396,   42,   23,   65,   50,   52,   23,   23,   47,
      396,  396,   57,   48,  396,   50,   51,   47,  396,   56,
       58,   23,   88,   59,   60,   61,   62,   63,   57,   23,
       47,   23,   71,   72,   72,   73,   72,  396,   73,   60,
       61,   62,   63,   75,  208,  205,  396,  396,  396,  396,
       65,   76,   77,   60,   61,   62,   78,   80,   81,   87,
       82,   83,   84,  396,   89,  396,   85,   23,  396,  396,
       73,  382,   81,   92,   82,  101,   90,  396,  396,  396,

       75,   76,   77,   60,   61,   62,   78,   94,  396,  396,
       80,   76,   77,  396,   83,   84,   98,  396,  396,   85,
       89,  396,  396,   87,   83,   84,  127,  103,  102,   89,
      128,  104,   90,  396,  101,   92,  105,  105,   94,   76,
       77,  108,  109,  110,  111,  113,  106,  114,  115,  223,
      220,  396,  396,  396,   98,   83,   84,  395,  116,  117,
      120,  121,  106,  118,  123,  124,  396,  102,   89,  144,
      125,  104,  396,  396,  103,  396,  105,  105,  131,  131,
      132,  130,  131,  396,  132,  393,  106,  396,  108,  109,
      110,  111,  134,  226,  205,  396,  396,  396,  396,  113,

      116,  117,  108,  109,  110,  118,  137,  396,  396,  120,
      116,  117,  396,  138,  144,  382,  144,  139,  140,  141,
      396,  139,  396,  144,  126,  150,  148,  127,  142,  396,
      145,  128,  146,  149,  130,  396,  127,  151,  390,  396,
      147,  396,  396,  132,  153,  137,  116,  117,  396,  396,
      396,  134,  155,  396,  108,  109,  110,  156,  156,  138,
      157,  157,  157,  139,  139,  139,  160,  139,  161,  149,
      344,  127,  166,  144,  144,  158,  158,  158,  138,  396,
      396,  163,  139,  140,  141,  144,  139,  236,  220,  144,
      150,  396,  150,  142,  396,  396,  153,  387,  396,  396,

      396,  157,  396,  162,  151,  167,  396,  164,  381,  396,
      165,  166,  168,  171,  155,  396,  158,  172,  396,  156,
      156,  396,  144,  144,  177,  183,  150,  170,  396,  396,
      174,  176,  168,  144,  178,  315,  396,  180,  181,  396,
      186,  175,  171,  182,  167,  185,  172,  396,  174,  144,
      171,  396,  144,  196,  196,  396,  196,  369,  396,  396,
      396,  196,  396,  185,  268,  171,  209,  396,  187,  190,
      197,  367,  198,  191,  192,  193,  144,  191,  199,  208,
      366,  210,  396,  209,  194,  396,  190,  204,  212,  209,
      191,  191,  191,  196,  191,  213,  196,  269,  210,  396,

      196,  223,  396,  215,  210,  190,  396,  396,  224,  191,
      192,  193,  196,  191,  220,  364,  209,  144,  396,  221,
      194,  396,  216,  396,  227,  396,  396,  396,  228,  396,
      214,  210,  205,  217,  226,  396,  396,  206,  396,  196,
      396,  230,  196,  227,  220,  396,  233,  230,  396,  221,
      232,  236,  396,  396,  239,  196,  351,  396,  231,  240,
      240,  396,  227,  245,  196,  244,  228,  396,  252,  241,
      396,  396,  196,  253,  255,  252,  250,  251,  396,  255,
      246,  396,  396,  239,  350,  396,  257,  315,  240,  240,
      258,  241,  396,  396,  244,  264,  227,  196,  241,  267,

      265,  260,  257,  396,  252,  396,  258,  396,  263,  253,
      272,  396,  256,  273,  257,  396,  396,  274,  260,  396,
      257,  277,  275,  278,  264,  280,  396,  396,  268,  265,
      257,  396,  196,  267,  264,  273,  281,  257,  396,  283,
      284,  287,  396,  272,  252,  285,  288,  288,  274,  290,
      396,  277,  274,  275,  293,  396,  280,  264,  303,  294,
      294,  269,  303,  348,  396,  303,  303,  313,  396,  295,
      297,  396,  396,  396,  298,  299,  300,  344,  298,  304,
      305,  287,  396,  306,  319,  301,  288,  288,  308,  309,
      290,  274,  310,  396,  396,  293,  341,  311,  315,  320,

      294,  294,  316,  295,  396,  396,  319,  340,  319,  303,
      295,  322,  297,  318,  323,  396,  298,  298,  298,  396,
      298,  320,  315,  320,  297,  303,  316,  303,  298,  299,
      300,  396,  298,  396,  325,  303,  328,  310,  307,  301,
      396,  396,  311,  324,  396,  396,  396,  326,  396,  324,
      333,  331,  396,  313,  310,  396,  327,  396,  314,  332,
      315,  396,  318,  319,  315,  396,  333,  396,  303,  303,
      334,  339,  331,  310,  396,  396,  336,  338,  320,  332,
      303,  315,  396,  342,  396,  333,  396,  337,  343,  343,
      333,  345,  346,  396,  334,  243,  336,  396,  333,  303,

      345,  303,  333,  342,  396,  396,  303,  396,  343,  343,
      330,  354,  396,  357,  363,  347,  355,  353,  358,  396,
      350,  359,  362,  303,  314,  354,  360,  307,  396,  396,
      355,  365,  396,  357,  354,  359,  257,  396,  368,  396,
      360,  362,  359,  371,  396,  365,  354,  291,  372,  372,
      375,  376,  368,  359,  377,  396,  396,  380,  373,  378,
      382,  371,  289,  396,  383,  373,  372,  372,  396,  396,
      377,  286,  388,  396,  279,  378,  373,  385,  396,  380,
      377,  382,  381,  396,  382,  383,  389,  385,  396,  382,
      391,  396,  396,  388,  377,  392,  392,  389,  184,  382,

      391,  396,  394,  271,  393,  392,  392,   22,  261,   22,
       22,  256,  249,  247,  243,  237,   22,   22,   24,  235,
      234,  214,  227,  227,   24,   35,  225,  219,  218,  202,
      201,  200,  188,  184,   35,   35,   49,  162,  171,   49,
       49,   54,   54,   64,   64,   64,   64,   67,   67,   70,
       70,   74,   74,   74,   79,   79,  171,  170,   79,   79,
       86,   86,  169,  154,   86,   86,   91,  136,  131,  126,
       99,   97,   95,   93,   91,   91,   96,   96,  100,  100,
      107,   72,   69,  107,   66,   53,   38,   47,   47,  107,
      107,  112,  112,  112,  112,  119,  119,   45,   23,  119,

      119,  122,  122,  129,   23,   13,  129,  129,  133,  133,
      133,  135,  396,  396,  396,  396,  135,  135,  143,  396,
      143,  143,  396,  396,  396,  396,  396,  143,  143,  152,
      396,  396,  396,  396,  396,  396,  396,  152,  152,  159,
      396,  396,  396,  396,  396,  396,  396,  396,  159,  159,
      173,  396,  396,  173,  173,  179,  179,  189,  189,  195,
      396,  195,  195,  396,  396,  396,  396,  396,  195,  195,
      203,  203,  207,  396,  396,  396,  207,  207,  211,  396,
      396,  396,  396,  396,  396,  396,  396,  211,  211,  222,
      396,  396,  396,  222,  222,  229,  396,  396,  229,  229,

      238,  238,  242,  396,  396,  242,  396,  396,  396,  396,
      396,  242,  242,  248,  248,  254,  396,  396,  396,  254,
      254,  259,  396,  396,  259,  259,  262,  262,  266,  396,
      396,  396,  266,  266,  270,  396,  396,  396,  396,  270,
      270,  276,  396,  396,  396,  276,  276,  282,  282,  292,
      292,  296,  396,  396,  296,  396,  396,  396,  396,  396,
      296,  296,  302,  396,  302,  302,  396,  396,  396,  396,
      396,  302,  302,  312,  396,  396,  396,  312,  312,  317,
      396,  396,  317,  317,  321,  396,  396,  396,  396,  396,
      396,  396,  396,  321,  321,  329,  396,  396,  396,  396,

      329,  329,  335,  396,  396,  335,  335,  349,  349,  352,
      352,  356,  396,  396,  396,  356,  356,  361,  396,  396,
      396,  361,  361,  370,  370,  374,  396,  396,  374,  396,
      396,  396,  396,  396,  374,  374,  379,  396,  396,  396,
      379,  379,  384,  396,  396,  384,  384,  386,  396,  396,
      396,  396,  386,  386,    3,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396

    } ;

static yyconst short int yy_chk[1292] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,   10,   56,    9,
        6,    6,    6,   12,    6,    6,    7,   11,   18,   56,
        7,    7,    7,    9,    7,   10,   13,   12,   13,   11,
       15,    7,   14,   18,   11,   25,   14,   14,   14,   15,
       14,   17,   25,   19,   20,   17,   17,   17,   19,   17,
       20,   23,   26,   27,   29,   27,   28,   23,   19,   20,
       21,   31,   27,   33,   21,   21,   21,  188,   21,   29,

       31,   32,  188,   32,   26,   21,   22,   28,   33,   34,
       22,   22,   22,   34,   22,   22,   35,   39,   40,   43,
       41,   22,   41,   44,   54,   35,   40,   52,   43,   48,
       54,   35,   49,   48,   49,   50,   39,   50,   49,   44,
       51,   59,   71,   52,   53,   53,   53,   53,   57,   51,
       57,   71,   59,   60,   60,   60,   62,   62,   62,   63,
       63,   63,   63,   64,  208,  208,   64,   64,   64,   64,
       65,   66,   66,   65,   65,   65,   66,   67,   68,   70,
       68,   69,   69,   67,   73,   70,   69,   68,   72,   72,
       72,  395,   81,   74,   81,   89,   73,   74,   74,   74,

       75,   78,   78,   75,   75,   75,   78,   79,   79,   79,
       80,   80,   80,   79,   85,   85,   86,   86,   86,   85,
       90,   91,   86,   87,   87,   87,  106,   91,   89,   92,
      106,   93,   90,   91,  101,   92,   93,   93,   94,   94,
       94,   95,   95,   95,   95,   96,   93,   97,   97,  223,
      223,   96,   97,   97,   98,   98,   98,  394,   99,   99,
      100,  102,   97,   99,  102,  102,  100,  101,  103,  122,
      102,  104,  107,  107,  103,  122,  104,  104,  108,  108,
      108,  107,  110,  110,  110,  392,  104,  107,  111,  111,
      111,  111,  112,  226,  226,  112,  112,  112,  112,  113,

      118,  118,  113,  113,  113,  118,  119,  119,  119,  120,
      120,  120,  119,  121,  124,  390,  123,  121,  121,  121,
      124,  121,  123,  125,  126,  132,  126,  128,  121,  125,
      123,  128,  124,  129,  130,  129,  130,  132,  386,  129,
      125,  131,  131,  131,  133,  137,  137,  137,  133,  133,
      133,  134,  136,  136,  134,  134,  134,  136,  136,  138,
      139,  140,  141,  138,  138,  138,  140,  138,  141,  149,
      382,  149,  150,  144,  145,  139,  140,  141,  142,  144,
      145,  145,  142,  142,  142,  146,  142,  236,  236,  147,
      153,  146,  151,  142,  143,  147,  153,  377,  143,  143,

      143,  157,  143,  143,  151,  150,  152,  146,  372,  143,
      147,  166,  152,  158,  155,  155,  157,  158,  152,  155,
      155,  159,  163,  164,  165,  170,  168,  170,  163,  164,
      159,  164,  168,  165,  167,  366,  159,  167,  167,  165,
      175,  163,  172,  167,  166,  173,  172,  173,  174,  175,
      174,  173,  176,  179,  181,  175,  180,  363,  176,  179,
      181,  182,  180,  185,  249,  185,  191,  182,  176,  178,
      180,  359,  181,  178,  178,  178,  187,  178,  182,  189,
      358,  191,  187,  192,  178,  189,  190,  187,  192,  193,
      190,  190,  190,  196,  190,  193,  197,  249,  192,  196,

      198,  203,  197,  197,  193,  194,  198,  203,  204,  194,
      194,  194,  199,  194,  202,  354,  209,  204,  199,  202,
      194,  195,  198,  204,  210,  195,  195,  195,  210,  195,
      195,  209,  206,  199,  207,  207,  195,  206,  211,  215,
      207,  230,  216,  230,  221,  215,  217,  211,  216,  221,
      216,  222,  222,  211,  225,  217,  346,  222,  215,  225,
      225,  217,  228,  231,  232,  229,  228,  229,  237,  225,
      232,  229,  231,  237,  255,  255,  235,  235,  231,  238,
      232,  235,  235,  239,  343,  238,  241,  341,  239,  239,
      241,  235,  242,  242,  244,  247,  244,  246,  239,  248,

      247,  242,  258,  246,  253,  248,  258,  242,  246,  253,
      254,  254,  256,  259,  256,  259,  254,  261,  260,  259,
      260,  262,  261,  263,  265,  266,  266,  262,  268,  265,
      340,  266,  263,  267,  267,  273,  269,  273,  263,  269,
      269,  271,  271,  272,  272,  269,  271,  271,  275,  276,
      276,  277,  277,  275,  279,  276,  280,  280,  282,  279,
      279,  268,  284,  339,  282,  283,  285,  292,  284,  279,
      281,  283,  285,  292,  281,  281,  281,  333,  281,  283,
      284,  287,  287,  285,  298,  281,  287,  287,  289,  289,
      290,  290,  291,  289,  289,  293,  329,  291,  295,  298,

      293,  293,  295,  289,  296,  296,  299,  328,  300,  303,
      293,  299,  297,  296,  300,  303,  297,  297,  297,  296,
      297,  299,  316,  300,  301,  305,  316,  304,  301,  301,
      301,  305,  301,  304,  304,  306,  307,  311,  307,  301,
      302,  306,  311,  324,  302,  302,  302,  305,  302,  302,
      323,  312,  312,  313,  313,  302,  306,  312,  314,  317,
      314,  317,  318,  319,  318,  317,  320,  321,  325,  326,
      320,  327,  331,  331,  325,  326,  321,  326,  319,  332,
      327,  332,  321,  330,  330,  322,  327,  325,  330,  330,
      334,  335,  337,  335,  334,  315,  336,  335,  336,  338,

      345,  337,  345,  342,  342,  338,  347,  337,  342,  342,
      310,  348,  347,  349,  353,  338,  348,  347,  350,  349,
      350,  351,  352,  353,  294,  355,  351,  288,  352,  353,
      355,  356,  356,  357,  357,  360,  286,  356,  361,  361,
      360,  362,  362,  364,  361,  365,  365,  278,  364,  364,
      367,  367,  368,  368,  369,  367,  367,  370,  364,  369,
      373,  371,  274,  370,  373,  367,  371,  371,  374,  374,
      378,  270,  379,  379,  264,  378,  371,  374,  379,  380,
      380,  383,  381,  374,  381,  383,  384,  385,  384,  385,
      387,  387,  384,  388,  388,  387,  387,  389,  257,  389,

      391,  391,  393,  252,  393,  391,  391,  397,  245,  397,
      397,  240,  234,  233,  227,  224,  397,  397,  398,  220,
      219,  214,  213,  212,  398,  399,  205,  201,  200,  186,
      184,  183,  177,  171,  399,  399,  400,  162,  161,  400,
      400,  401,  401,  402,  402,  402,  402,  403,  403,  404,
      404,  405,  405,  405,  406,  406,  160,  156,  406,  406,
      407,  407,  154,  135,  407,  407,  408,  116,  109,  105,
       88,   83,   82,   76,  408,  408,  409,  409,  410,  410,
      411,   61,   58,  411,   55,   42,   38,   37,   36,  411,
      411,  412,  412,  412,  412,  413,  413,   30,   24,  413,

      413,  414,  414,  415,    8,    5,  415,  415,  416,  416,
      416,  417,    3,    0,    0,    0,  417,  417,  418,    0,
      418,  418,    0,    0,    0,    0,    0,  418,  418,  419,
        0,    0,    0,    0,    0,    0,    0,  419,  419,  420,
        0,    0,    0,    0,    0,    0,    0,    0,  420,  420,
      421,    0,    0,  421,  421,  422,  422,  423,  423,  424,
        0,  424,  424,    0,    0,    0,    0,    0,  424,  424,
      425,  425,  426,    0,    0,    0,  426,  426,  427,    0,
        0,    0,    0,    0,    0,    0,    0,  427,  427,  428,
        0,    0,    0,  428,  428,  429,    0,    0,  429,  429,

      430,  430,  431,    0,    0,  431,    0,    0,    0,    0,
        0,  431,  431,  432,  432,  433,    0,    0,    0,  433,
      433,  434,    0,    0,  434,  434,  435,  435,  436,    0,
        0,    0,  436,  436,  437,    0,    0,    0,    0,  437,
      437,  438,    0,    0,    0,  438,  438,  439,  439,  440,
      440,  441,    0,    0,  441,    0,    0,    0,    0,    0,
      441,  441,  442,    0,  442,  442,    0,    0,    0,    0,
        0,  442,  442,  443,    0,    0,    0,  443,  443,  444,
        0,    0,  444,  444,  445,    0,    0,    0,    0,    0,
        0,    0,    0,  445,  445,  446,    0,    0,    0,    0,

      446,  446,  447,    0,    0,  447,  447,  448,  448,  449,
      449,  450,    0,    0,    0,  450,  450,  451,    0,    0,
        0,  451,  451,  452,  452,  453,    0,    0,  453,    0,
        0,    0,    0,    0,  453,  453,  454,    0,    0,    0,
      454,  454,  455,    0,    0,  455,  455,  456,    0,    0,
        0,    0,  456,  456,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\Proyecto.l"
#define INITIAL 0
#line 2 ".\\Proyecto.l"
#include <stdio.h>
#include <stdlib.h>
/*** Puesto a ser probado

CONDICIONAL_FOR {PAR_AB}{ASIGNAR}*{SIGNO_PTOCOMA}{CONDICIONAL}{INSTRUCCION}{PAR_CE}
***/
#line 798 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 76 ".\\Proyecto.l"

#line 951 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 397 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1255 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 ".\\Proyecto.l"
{printf ("es un numero entero - ");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 ".\\Proyecto.l"
{printf ("Esto es una variable - ");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 79 ".\\Proyecto.l"
{printf ("Asignacion de variable - ");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 ".\\Proyecto.l"
{printf ("Asignacion entero a variable - ");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 81 ".\\Proyecto.l"
{printf ("Esto es un while completo- ");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 ".\\Proyecto.l"
{printf ("Este es un tipo de dato - ");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 ".\\Proyecto.l"
{printf ("Este es una operacion- ");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 ".\\Proyecto.l"
{printf ("Este es un if sin else- ");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 ".\\Proyecto.l"
{printf ("Este es un if COMPLETO CON ELSE- ");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 ".\\Proyecto.l"
{printf ("Este es una asignacion de CHAR- ");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 ".\\Proyecto.l"
{printf ("Este es una asignacion de DOUBLE- ");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 88 ".\\Proyecto.l"
{printf ("Esto es un double- ");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 ".\\Proyecto.l"
{printf ("Esto es LA DEFINICION DE UN ENTERO- ");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 ".\\Proyecto.l"
{printf ("Esto es LA DEFINICION DE UN CHAR- ");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 ".\\Proyecto.l"
{printf ("Esto es LA DEFINICION DE UN DOUBLE- ");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 ".\\Proyecto.l"
{printf ("Esto es una operacion entre VARIABLES- ");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 ".\\Proyecto.l"
ECHO;
	YY_BREAK
#line 1119 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 397 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 397 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 396);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 93 ".\\Proyecto.l"


int main (int argc, char *argv[])
{
   if (argc == 2)
   {
      yyin = fopen (argv[1], "rt");
      if (yyin == NULL)
      {
         printf ("El fichero %s no se puede abrir\n", argv[1]);
         exit (-1);
      }
   }
  else 
     yyin = stdin;
  yylex ();
   return 0;
  
}

int yywrap ()
{
  return 1;
}